<?php
add_action( 'wp_enqueue_scripts', 'wdjewelry_eidt_customize_css_footer' );
if(!function_exists('wdjewelry_eidt_customize_css_footer')){
	function wdjewelry_eidt_customize_css_footer(){ 
		/********SETTING CUSSTOM CSS HEADER*******/ 
		//btn
		$custom_css = '';
		$custom_css .= '.footer_top_bg, .footer-content-top{background-color:'.get_theme_mod('footer_top_bg','#fff').'}';
		$custom_css .= '.footer_top_border, .footer-content-top, .footer-content-top *{border-color:'.get_theme_mod('footer_top_border','#e5e5e5').'}';
		$custom_css .= '.footer_top_heading, .footer-content-top h1, .footer-content-top h2, .footer-content-top h3, .footer-content-top h4, .footer-content-top h5, .footer-content-top h6, .footer-content-top .widget-title, .footer-content-top .widgettitle{color:'.get_theme_mod('footer_top_heading','#000').'}';
		$custom_css .= '.footer_top_text, .footer-content-top{color:'.get_theme_mod('footer_top_text','#000000').'}';
		$custom_css .= '.footer_top_link, .footer-content-top a, .footer-content-top .widget_tag_cloud a:hover {color:'.get_theme_mod('footer_top_link','#fff').'}';
		$custom_css .= '.footer_top_link_hover, .footer-content-top a:hover{color:'.get_theme_mod('footer_top_link_hover','green').'}';
		$custom_css .= '.footer_main_bg, .footer-content-main{background:'.get_theme_mod('footer_main_bg','#fff').'}';
		$custom_css .= '.footer_main_border, .footer-content-main, .footer-content-main * {border-color:'.get_theme_mod('footer_main_border','#e5e5e5').'}';
		$custom_css .= '.footer_main_heading, .footer-content-main h1, .footer-content-main h2, .footer-content-main h3, .footer-content-main h4, .footer-content-main h5, .footer-content-main h6, .footer-content-main .widget-title, .footer-content-main .widgettitle{color:'.get_theme_mod('footer_main_heading','#000').'}';
		$custom_css .= '.footer_main_text, .footer-content-main{color:'.get_theme_mod('footer_main_text','#000000').'}';
		$custom_css .= '.footer_main_link, .footer-content-main a, .footer-content-main .widget_tag_cloud a:hover{color:'.get_theme_mod('footer_main_link','#000000').'}';
		$custom_css .= '.footer_main_link_hover, .footer-content-main a:hover{color:'.get_theme_mod('footer_main_link_hover','#a07936').'}';
		$custom_css .= '.footer_bottom_bg, .footer-content-bottom{background:'.get_theme_mod('footer_bottom_bg','#21201f').'}';
		$custom_css .= '.footer_bottom_heading, .footer-content-bottom h1, .footer-content-bottom h2, .footer-content-bottom h3, .footer-content-bottom h4, .footer-content-bottom h5, .footer-content-bottom h6, .footer-content-bottom .widget-title, .footer-content-bottom .widgettitle {color:'.get_theme_mod('footer_bottom_heading','#e0e0e0').'}';
		$custom_css .= '.footer_bottom_link, .footer-content-bottom a, .footer-content-bottom .widget_tag_cloud a:hover{color:'.get_theme_mod('footer_bottom_link','#fff').'}';
		$custom_css .= '.footer_bottom_link_hover, .footer-content-bottom a:hover{color:'.get_theme_mod('footer_bottom_link_hover','#e0e0e0').'}';
		$custom_css .= '.footer_bottom_text, .footer-content-bottom{color:'.get_theme_mod('footer_bottom_text','#9e9e9e').'}';
		$custom_css .= '.footer_bottom_border, .footer-content-bottom, .footer-content-bottom *{border-color:'.get_theme_mod('footer_bottom_heading','#9e9e9e').'}';


		$custom_css .= '.footer_btn,.site-footer button,.site-footer .button,.site-footer input[type="button"],.site-footer input[type="reset"],.site-footer input[type="submit"],.site-footer .vc_btn3,.site-footer .clear-all,.site-footer .woocommerce #respond input#submit,.site-footer .woocommerce a.button,.site-footer .woocommerce button.button,.site-footer .woocommerce input.button,.woocommerce .site-footer button,.woocommerce .site-footer .button,.woocommerce .site-footer input[type="button"],.woocommerce .site-footer input[type="reset"],.woocommerce .site-footer input[type="submit"],.woocommerce .site-footer .vc_btn3,.woocommerce .site-footer .clear-all{background-color:'.get_theme_mod('footer_btn_bg','#a07936').'}';
		$custom_css .= '.footer_btn,.site-footer button,.site-footer .button,.site-footer input[type="button"],.site-footer input[type="reset"],.site-footer input[type="submit"],.site-footer .vc_btn3,.site-footer .clear-all,.site-footer .woocommerce #respond input#submit,.site-footer .woocommerce a.button,.site-footer .woocommerce button.button,.site-footer .woocommerce input.button,.woocommerce .site-footer button,.woocommerce .site-footer .button,.woocommerce .site-footer input[type="button"],.woocommerce .site-footer input[type="reset"],.woocommerce .site-footer input[type="submit"],.woocommerce .site-footer .vc_btn3,.woocommerce .site-footer .clear-all{color:'.get_theme_mod('footer_btn_color','#fff').'}';
		$custom_css .= '.footer_btn,.site-footer button,.site-footer .button,.site-footer input[type="button"],.site-footer input[type="reset"],.site-footer input[type="submit"],.site-footer .vc_btn3,.site-footer .clear-all,.site-footer .woocommerce #respond input#submit,.site-footer .woocommerce a.button,.site-footer .woocommerce button.button,.site-footer .woocommerce input.button,.woocommerce .site-footer button,.woocommerce .site-footer .button,.woocommerce .site-footer input[type="button"],.woocommerce .site-footer input[type="reset"],.woocommerce .site-footer input[type="submit"],.woocommerce .site-footer .vc_btn3,.woocommerce .site-footer .clear-all{border-color:'.get_theme_mod('footer_btn_bd','#a07936').'}';

		$custom_css .= '.footer_btn:hover,.site-footer button:hover,.site-footer .button:hover,.site-footer input[type="button"]:hover,.site-footer input[type="reset"]:hover,.site-footer input[type="submit"]:hover,.site-footer .vc_btn3:hover,.site-footer .clear-all:hover,.site-footer .woocommerce #respond input#submit:hover,.site-footer .woocommerce a.button:hover,.site-footer .woocommerce button.button:hover,.site-footer .woocommerce input.button:hover,.footer_btn:focus,.site-footer button:focus,.site-footer .button:focus,.site-footer input[type="button"]:focus,.site-footer input[type="reset"]:focus,.site-footer input[type="submit"]:focus,.site-footer .vc_btn3:focus,.site-footer .clear-all:focus,.site-footer .woocommerce #respond input#submit:focus,.site-footer .woocommerce a.button:focus,.site-footer .woocommerce button.button:focus,.site-footer .woocommerce input.button:focus,.site-footer button:hover,.site-footer button:focus,.site-footer .button:hover,.site-footer .button:focus,.site-footer input[type="button"]:hover,.site-footer input[type="button"]:focus,.site-footer input[type="reset"]:hover,.site-footer input[type="reset"]:focus,.site-footer input[type="submit"]:hover,.site-footer input[type="submit"]:focus,.site-footer .vc_btn3:hover,.site-footer .vc_btn3:focus,.site-footer .clear-all:hover,.site-footer .clear-all:focus,.site-footer .woocommerce #respond input#submit:hover,.site-footer .woocommerce #respond input#submit:focus,.site-footer .woocommerce a.button:hover,.site-footer .woocommerce a.button:focus,.site-footer .woocommerce button.button:hover,.site-footer .woocommerce button.button:focus,.site-footer .woocommerce input.button:hover,.site-footer .woocommerce input.button:focus,.woocommerce .site-footer button:hover,.woocommerce .site-footer button:focus,.woocommerce .site-footer .button:hover,.woocommerce .site-footer .button:focus,.woocommerce .site-footer input[type="button"]:hover,.woocommerce .site-footer input[type="button"]:focus,.woocommerce .site-footer input[type="reset"]:hover,.woocommerce .site-footer input[type="reset"]:focus,.woocommerce .site-footer input[type="submit"]:hover,.woocommerce .site-footer input[type="submit"]:focus,.woocommerce .site-footer .vc_btn3:hover,.woocommerce .site-footer .vc_btn3:focus,.woocommerce .site-footer .clear-all:hover,.woocommerce .site-footer .clear-all:focus{background-color:'.get_theme_mod('footer_btn_bg_hv','#fff').'}';
		$custom_css .= '.footer_btn:hover,.site-footer button:hover,.site-footer .button:hover,.site-footer input[type="button"]:hover,.site-footer input[type="reset"]:hover,.site-footer input[type="submit"]:hover,.site-footer .vc_btn3:hover,.site-footer .clear-all:hover,.site-footer .woocommerce #respond input#submit:hover,.site-footer .woocommerce a.button:hover,.site-footer .woocommerce button.button:hover,.site-footer .woocommerce input.button:hover,.footer_btn:focus,.site-footer button:focus,.site-footer .button:focus,.site-footer input[type="button"]:focus,.site-footer input[type="reset"]:focus,.site-footer input[type="submit"]:focus,.site-footer .vc_btn3:focus,.site-footer .clear-all:focus,.site-footer .woocommerce #respond input#submit:focus,.site-footer .woocommerce a.button:focus,.site-footer .woocommerce button.button:focus,.site-footer .woocommerce input.button:focus,.site-footer button:hover,.site-footer button:focus,.site-footer .button:hover,.site-footer .button:focus,.site-footer input[type="button"]:hover,.site-footer input[type="button"]:focus,.site-footer input[type="reset"]:hover,.site-footer input[type="reset"]:focus,.site-footer input[type="submit"]:hover,.site-footer input[type="submit"]:focus,.site-footer .vc_btn3:hover,.site-footer .vc_btn3:focus,.site-footer .clear-all:hover,.site-footer .clear-all:focus,.site-footer .woocommerce #respond input#submit:hover,.site-footer .woocommerce #respond input#submit:focus,.site-footer .woocommerce a.button:hover,.site-footer .woocommerce a.button:focus,.site-footer .woocommerce button.button:hover,.site-footer .woocommerce button.button:focus,.site-footer .woocommerce input.button:hover,.site-footer .woocommerce input.button:focus,.woocommerce .site-footer button:hover,.woocommerce .site-footer button:focus,.woocommerce .site-footer .button:hover,.woocommerce .site-footer .button:focus,.woocommerce .site-footer input[type="button"]:hover,.woocommerce .site-footer input[type="button"]:focus,.woocommerce .site-footer input[type="reset"]:hover,.woocommerce .site-footer input[type="reset"]:focus,.woocommerce .site-footer input[type="submit"]:hover,.woocommerce .site-footer input[type="submit"]:focus,.woocommerce .site-footer .vc_btn3:hover,.woocommerce .site-footer .vc_btn3:focus,.woocommerce .site-footer .clear-all:hover,.woocommerce .site-footer .clear-all:focus{color:'.get_theme_mod('footer_btn_color_hv','#a07936').'}';
		$custom_css .= '.footer_btn:hover,.site-footer button:hover,.site-footer .button:hover,.site-footer input[type="button"]:hover,.site-footer input[type="reset"]:hover,.site-footer input[type="submit"]:hover,.site-footer .vc_btn3:hover,.site-footer .clear-all:hover,.site-footer .woocommerce #respond input#submit:hover,.site-footer .woocommerce a.button:hover,.site-footer .woocommerce button.button:hover,.site-footer .woocommerce input.button:hover,.footer_btn:focus,.site-footer button:focus,.site-footer .button:focus,.site-footer input[type="button"]:focus,.site-footer input[type="reset"]:focus,.site-footer input[type="submit"]:focus,.site-footer .vc_btn3:focus,.site-footer .clear-all:focus,.site-footer .woocommerce #respond input#submit:focus,.site-footer .woocommerce a.button:focus,.site-footer .woocommerce button.button:focus,.site-footer .woocommerce input.button:focus,.site-footer button:hover,.site-footer button:focus,.site-footer .button:hover,.site-footer .button:focus,.site-footer input[type="button"]:hover,.site-footer input[type="button"]:focus,.site-footer input[type="reset"]:hover,.site-footer input[type="reset"]:focus,.site-footer input[type="submit"]:hover,.site-footer input[type="submit"]:focus,.site-footer .vc_btn3:hover,.site-footer .vc_btn3:focus,.site-footer .clear-all:hover,.site-footer .clear-all:focus,.site-footer .woocommerce #respond input#submit:hover,.site-footer .woocommerce #respond input#submit:focus,.site-footer .woocommerce a.button:hover,.site-footer .woocommerce a.button:focus,.site-footer .woocommerce button.button:hover,.site-footer .woocommerce button.button:focus,.site-footer .woocommerce input.button:hover,.site-footer .woocommerce input.button:focus,.woocommerce .site-footer button:hover,.woocommerce .site-footer button:focus,.woocommerce .site-footer .button:hover,.woocommerce .site-footer .button:focus,.woocommerce .site-footer input[type="button"]:hover,.woocommerce .site-footer input[type="button"]:focus,.woocommerce .site-footer input[type="reset"]:hover,.woocommerce .site-footer input[type="reset"]:focus,.woocommerce .site-footer input[type="submit"]:hover,.woocommerce .site-footer input[type="submit"]:focus,.woocommerce .site-footer .vc_btn3:hover,.woocommerce .site-footer .vc_btn3:focus,.woocommerce .site-footer .clear-all:hover,.woocommerce .site-footer .clear-all:focus{border-color:'.get_theme_mod('footer_btn_bd_hv','#e5e5e5').'}';

		wp_add_inline_style('wdjewelry-main.css',$custom_css);
	}

}		