<?php
add_action( 'wp_enqueue_scripts', 'wdjewelry_eidt_customize_css' );
if(!function_exists('wdjewelry_eidt_customize_css')){
	function wdjewelry_eidt_customize_css(){ 
		/********SETTING CUSSTOM CSS BODY*******/ 
		$custom_css  = '';
		$custom_css .= 'body{font-family:'.'"'.get_theme_mod("tvlgiao_wpdance_body_font",'Lato').'"'.', Helvetica, Arial, sans-serif}';
		$custom_css	.= 'body{font-size:'.get_theme_mod("tvlgiao_wpdance_body_font_size",'14px').'}';
		$custom_css	.= "body{color:".get_theme_mod('tvlgiao_wpdance_body_font_color','black')."}";

		/********SETTING CUSSTOM CSS H1*******/

		$custom_css .= 'h1,.h1{font-family:'.'"'.get_theme_mod('tvlgiao_wpdance_h1_font','Belleza').'"'.', Helvetica, Arial, sans-serif}';
		$custom_css .= "h1,.h1{font-size:".get_theme_mod('tvlgiao_wpdance_h1_font_size','30px')."}";
		$custom_css .= "h1,.h1,h1 a,.h1 a{color:".get_theme_mod('tvlgiao_wpdance_h1_font_color','black')."}";

		 /********SETTING CUSSTOM CSS H2*******/ 
		$custom_css .= 'h2,.h2{font-family:'.'"'.get_theme_mod('tvlgiao_wpdance_h2_font','Belleza').'"'.', Helvetica, Arial, sans-serif}';
		$custom_css .= "h2,.h2{font-size:".get_theme_mod('tvlgiao_wpdance_h2_font_size','28px')."}";
		$custom_css .= "h2,.h2,h2 a,.h2 a{color:".get_theme_mod('tvlgiao_wpdance_h2_font_color','black')."}";

		 /********SETTING CUSSTOM CSS H3*******/ 
		$custom_css .= 'h3,.h3{font-family:'.'"'.get_theme_mod('tvlgiao_wpdance_h3_font','Belleza').'"'.', Helvetica, Arial, sans-serif}';
		$custom_css .= "h3,.h3{font-size:".get_theme_mod('tvlgiao_wpdance_h3_font_size','24px')."}";
		$custom_css .= "h3 a,.h3 a{color:".get_theme_mod('tvlgiao_wpdance_h3_font_color','black')."}";

		 /********SETTING CUSSTOM CSS H4*******/ 
		$custom_css .= 'h4,.h4{font-family:'.'"'.get_theme_mod('tvlgiao_wpdance_h4_font','Belleza').'"'.', Helvetica, Arial, sans-serif}';
		$custom_css .= "h4,.h4{font-size:".get_theme_mod('tvlgiao_wpdance_h4_font_size','20px')."}";
		$custom_css .= "h4 a,.h4 a{color:".get_theme_mod('tvlgiao_wpdance_h4_font_color','black')."}";
	
		/********SETTING CUSSTOM CSS H5*******/ 
		$custom_css .= 'h5,.h5{font-family:'.'"'.get_theme_mod('tvlgiao_wpdance_h5_font','Belleza').'"'.', Helvetica, Arial, sans-serif}';
		$custom_css .= "h5,.h5{font-size:".get_theme_mod('tvlgiao_wpdance_h5_font_size','16px')."}";
		$custom_css .= "h5,.h5,h5 a,.h5 a{color:".get_theme_mod('tvlgiao_wpdance_h5_font_color','black')."}";

		/********SETTING CUSSTOM CSS H6*******/ 
		$custom_css .= 'h6,.h6{font-family:'.'"'.get_theme_mod('tvlgiao_wpdance_h6_font','Belleza').'"'.', Helvetica, Arial, sans-serif}';
		$custom_css .= "h6,.h6{font-size:".get_theme_mod('tvlgiao_wpdance_h6_font_size','14px')."}";
		$custom_css .= "h6,.h6,h6 a,.h6 a{color:".get_theme_mod('tvlgiao_wpdance_h6_font_color','black')."}";

		/********CUSTOM CSS COLOR*********/

		$custom_css .= '.primary_bg,.woocommerce div.product .woocommerce-tabs ul.tabs li.active a,.link_bg,.home .cart_content .wd_mini_cart > span span,.mobile-cart .cart-mini-content .mobile_cart a span,.woocommerce nav.woocommerce-pagination span.current,.woocommerce nav.woocommerce-pagination ul li span.current,.woocommerce nav.woocommerce-pagination a:hover,.woocommerce nav.woocommerce-pagination ul li a:hover,.woocommerce-page nav.woocommerce-pagination span.current,.woocommerce-page nav.woocommerce-pagination ul li span.current,.woocommerce-page nav.woocommerce-pagination a:hover,.woocommerce-page nav.woocommerce-pagination ul li a:hover,.navigation span.current,.navigation ul li span.current,.navigation a:hover,.navigation ul li a:hover,.recent_blogs_horizontal_container .rb_item .rb_row_left span:first-child,#today,.woocommerce .widget_price_filter .price_slider_wrapper .ui-widget-content,.woocommerce.widget_price_filter .price_slider_wrapper .ui-widget-content,.woocommerce-page .widget_price_filter .price_slider_wrapper .ui-widget-content,.woocommerce-page.widget_price_filter .price_slider_wrapper .ui-widget-content,.woocommerce .price_slider_wrapper .ui-widget-content,.woocommerce-page .price_slider_wrapper .ui-widget-content{ background-color:'.get_theme_mod('primary_bg','#a07936').'}';
		$custom_css .= '.secondary_bg, .ts-vcsc-box-icon.icon_top-style:before, .woocommerce .widget_price_filter .ui-slider .ui-slider-range, .woocommerce.widget_price_filter .ui-slider .ui-slider-range, .woocommerce-page .widget_price_filter .ui-slider .ui-slider-range, .woocommerce-page.widget_price_filter .ui-slider .ui-slider-range{ background-color:'.get_theme_mod('secondary_bg','#f2e4cc').'}';
		$custom_css .= '.body_bg, body { background-color:'.get_theme_mod('body_bg','#f7f7f7').'}';
		$custom_css .= '.breadcrumb_bg, .site-header .breadcrumbs{ background-color:'.get_theme_mod('breadcrumb_bg','#f2e4cc').'}';
		$custom_css .= '.breadcrumb_color, .site-header .breadcrumbs{color:'.get_theme_mod('breadcrumb_color','#a07936').'}';
		$custom_css .= '.breadcrumb_link, .site-header .breadcrumbs a{color:'.get_theme_mod('breadcrumb_link','#808080').'}';
		$custom_css .= '.breadcrumb_link_hover, .site-header .breadcrumbs a:hover{color:'.get_theme_mod('breadcrumb_link_hover','#a07936').'}';
		//heading h
		$custom_css .= '.heading_h1_color, .single-post .related_post .content_title h3 a, .single-post .comment .content_title h3 a, h1, .h1, div#wd-teammate-style-1 .ts-teammate-icons a, div#wd-teammate-style-1 .wd-teammate-content .wd-temmate-tittle, div.ts-team2 .ts-teammate-icons a, div.ts-team3 .ts-teammate-icons a, .rb_title a {color:'.get_theme_mod('heading_h1_color','#010101').'}';
		$custom_css .= '.heading_h2_color, h2, .h2 {color:'.get_theme_mod('heading_h2_color','#010101').'}';
		$custom_css .= '.heading_h3_color, h3, .h3 {color:'.get_theme_mod('heading_h3_color','#010101').'}';
		$custom_css .= '.heading_h4_color, h4, .h4{color:'.get_theme_mod('heading_h4_color','#010101').'}';
		$custom_css .= '.heading_h5_color, h5, .h5{color:'.get_theme_mod('heading_h5_color','#010101').'}';
		$custom_css .= '.heading_h6_color, h6, .h6{color:'.get_theme_mod('heading_h6_color','#010101').'}';
		//text
		$custom_css .= '.text, .woocommerce .products li.product .price del, .woocommerce-page .products li.product .price del, .woocommerce div.product .summary .woocs_price_code del, .woocommerce div.product .posted_in a, .woocommerce div.product .tagged_as a, .woocommerce div.product .content-measurements a, .woocommerce div.product .content-shipping a, .woocommerce div.product .content-size-chart a, .woocommerce div.product #tab-reviews #reply-title, .content_blog .wd_link_home a, .single-post .related_post .wd-url-home a, .single-post .comment .wd-url-home a, .single-post .wd_content_single .wd_single_home a, .single-post .wd_content_single .wd_single_tag a, body, .woocommerce nav.woocommerce-pagination a, .woocommerce-page nav.woocommerce-pagination a, .navigation a, #comments ol li .date_comment a, #comments ol li .comment-reply-link  {color:'.get_theme_mod('text ','#272727').'}';
		$custom_css .= '.border_color, .woocommerce .woocommerce-cart .product-quantity .quantity button, .woocommerce.woocommerce-cart .product-quantity .quantity button, .woocommerce-page .woocommerce-cart .product-quantity .quantity button, .woocommerce-page.woocommerce-cart .product-quantity .quantity button, .woocommerce div.product .quantity button, *, *:before, *:after{ border-color:'.get_theme_mod('border_color','#d9d9d9').'}';
		$custom_css .= '.link,h1 a:hover,.h1 a:hover,h2 a:hover,.h2 a:hover,h3 a:hover,.h3 a:hover,h4 a:hover,.h4 a:hover,h5 a:hover,.h5 a:hover,h6 a:hover,.h6 a:hover, .woocommerce div.product .content-measurements a:hover, .woocommerce div.product .content-shipping a:hover, .woocommerce div.product .content-size-chart a:hover, .content_blog .content_title h3:hover, .single-post .wd_content_single .wd_single_title .entry-title:hover, .single-post .related_post .related_title h3:hover, .single-post .comment .related_title h3:hover, .single-post .related_post #comments h3:hover, .single-post .comment #comments h3:hover, a, .woocommerce .products.list .add_to_cart_button.button:hover, .woocommerce .products.list .product_type_simple.button:hover, .woocommerce ul.products.list .add_to_cart_button.button:hover, .woocommerce ul.products.list .product_type_simple.button:hover, .woocommerce-page .products.list .add_to_cart_button.button:hover, .woocommerce-page .products.list .product_type_simple.button:hover, .woocommerce-page ul.products.list .add_to_cart_button.button:hover, .woocommerce-page ul.products.list .product_type_simple.button:hover, .woocommerce .products.list .wd_quickshop_handler:hover, .woocommerce ul.products.list .wd_quickshop_handler:hover, .woocommerce-page .products.list .wd_quickshop_handler:hover, .woocommerce-page ul.products.list .wd_quickshop_handler:hover, .woocommerce .products.list .compare-button:hover, .woocommerce ul.products.list .compare-button:hover, .woocommerce-page .products.list .compare-button:hover, .woocommerce-page ul.products.list .compare-button:hover, .woocommerce .products.list .yith-wcwl-add-to-wishlist:hover, .woocommerce ul.products.list .yith-wcwl-add-to-wishlist:hover, .woocommerce-page .products.list .yith-wcwl-add-to-wishlist:hover, .woocommerce-page ul.products.list .yith-wcwl-add-to-wishlist:hover, .woocommerce div.product .compare-button:hover, .woocommerce div.product .yith-wcwl-add-to-wishlist:hover, #comments ol li .comment-reply-link:hover, .rb_title a:hover {color:'.get_theme_mod('link','#eec989').'}';
		$custom_css .= '.link_hover, a:hover{color:'.get_theme_mod('link_hover','#272727').'}';
		$custom_css .= '.icon, .woocommerce .products.grid li.product .add_to_cart_button:before, .woocommerce .products.grid li.product .product_type_simple:before, .woocommerce ul.products.grid li.product .add_to_cart_button:before, .woocommerce ul.products.grid li.product .product_type_simple:before, .woocommerce-page .products.grid li.product .add_to_cart_button:before, .woocommerce-page .products.grid li.product .product_type_simple:before, .woocommerce-page ul.products.grid li.product .add_to_cart_button:before, .woocommerce-page ul.products.grid li.product .product_type_simple:before, .woocommerce .products.grid li.product .wd_quickshop_handler:before, .woocommerce ul.products.grid li.product .wd_quickshop_handler:before, .woocommerce-page .products.grid li.product .wd_quickshop_handler:before, .woocommerce-page ul.products.grid li.product .wd_quickshop_handler:before, .woocommerce .products.grid li.product .compare-button:before, .woocommerce ul.products.grid li.product .compare-button:before, .woocommerce-page .products.grid li.product .compare-button:before, .woocommerce-page ul.products.grid li.product .compare-button:before, .woocommerce .products.grid li.product .yith-wcwl-add-to-wishlist:before, .woocommerce ul.products.grid li.product .yith-wcwl-add-to-wishlist:before, .woocommerce-page .products.grid li.product .yith-wcwl-add-to-wishlist:before, .woocommerce-page ul.products.grid li.product .yith-wcwl-add-to-wishlist:before {color:'.get_theme_mod('icon','#808080').'}';
	
		//btn
		$custom_css .= '.btn,button,.button,input.button,input[type="button"],input[type="reset"],input[type="submit"],.vc_btn3,.clear-all,.woocommerce #respond input#submit,.woocommerce a.button,.woocommerce button.button,.woocommerce input.button[type^="submit"],.woocommerce-page #respond input#submit,.woocommerce-page a.button,.woocommerce-page button.button,.woocommerce-page input.button[type^="submit"],.woocommerce #respond input#submit:disabled,.woocommerce #respond input#submit[disabled]:disabled,.woocommerce a.button:disabled,.woocommerce a.button[disabled]:disabled,.woocommerce button.button:disabled,.woocommerce button.button[disabled]:disabled,.woocommerce input.button[type^="submit"]:disabled,.woocommerce input.button[type^="submit"][disabled]:disabled,.woocommerce-page #respond input#submit:disabled,.woocommerce-page #respond input#submit[disabled]:disabled,.woocommerce-page a.button:disabled,.woocommerce-page a.button[disabled]:disabled,.woocommerce-page button.button:disabled,.woocommerce-page button.button[disabled]:disabled,.woocommerce-page input.button[type^="submit"]:disabled,.woocommerce-page input.button[type^="submit"][disabled]:disabled, .woocommerce #respond input#submit.alt, .woocommerce a.button.alt, .woocommerce button.button.alt, .woocommerce input.button.alt{color:'.get_theme_mod('color_btn','#fff').'}';
		$custom_css .= '.btn,button,.button,input.button,input[type="button"],input[type="reset"],input[type="submit"],.vc_btn3,.clear-all,.woocommerce #respond input#submit,.woocommerce a.button,.woocommerce button.button,.woocommerce input.button[type^="submit"],.woocommerce-page #respond input#submit,.woocommerce-page a.button,.woocommerce-page button.button,.woocommerce-page input.button[type^="submit"],.woocommerce #respond input#submit:disabled,.woocommerce #respond input#submit[disabled]:disabled,.woocommerce a.button:disabled,.woocommerce a.button[disabled]:disabled,.woocommerce button.button:disabled,.woocommerce button.button[disabled]:disabled,.woocommerce input.button[type^="submit"]:disabled,.woocommerce input.button[type^="submit"][disabled]:disabled,.woocommerce-page #respond input#submit:disabled,.woocommerce-page #respond input#submit[disabled]:disabled,.woocommerce-page a.button:disabled,.woocommerce-page a.button[disabled]:disabled,.woocommerce-page button.button:disabled,.woocommerce-page button.button[disabled]:disabled,.woocommerce-page input.button[type^="submit"]:disabled,.woocommerce-page input.button[type^="submit"][disabled]:disabled, .woocommerce #respond input#submit.alt, .woocommerce a.button.alt, .woocommerce button.button.alt, .woocommerce input.button.alt{background-color:'.get_theme_mod('background_btn','#a07936').'}';
		$custom_css .= '.btn,button,.button,input.button,input[type="button"],input[type="reset"],input[type="submit"],.vc_btn3,.clear-all,.woocommerce #respond input#submit,.woocommerce a.button,.woocommerce button.button,.woocommerce input.button[type^="submit"],.woocommerce-page #respond input#submit,.woocommerce-page a.button,.woocommerce-page button.button,.woocommerce-page input.button[type^="submit"],.woocommerce #respond input#submit:disabled,.woocommerce #respond input#submit[disabled]:disabled,.woocommerce a.button:disabled,.woocommerce a.button[disabled]:disabled,.woocommerce button.button:disabled,.woocommerce button.button[disabled]:disabled,.woocommerce input.button[type^="submit"]:disabled,.woocommerce input.button[type^="submit"][disabled]:disabled,.woocommerce-page #respond input#submit:disabled,.woocommerce-page #respond input#submit[disabled]:disabled,.woocommerce-page a.button:disabled,.woocommerce-page a.button[disabled]:disabled,.woocommerce-page button.button:disabled,.woocommerce-page button.button[disabled]:disabled,.woocommerce-page input.button[type^="submit"]:disabled,.woocommerce-page input.button[type^="submit"][disabled]:disabled, .woocommerce #respond input#submit.alt, .woocommerce a.button.alt, .woocommerce button.button.alt, .woocommerce input.button.alt{border-color:'.get_theme_mod('border_btn','#a07936').'}';
		//hover
		$custom_css .= '.btn:hover,button:hover,.button:hover,input[type="button"]:hover,input[type="reset"]:hover,input[type="submit"]:hover,.vc_btn3:hover,.clear-all:hover,.woocommerce #respond input#submit:hover,.woocommerce a.button:hover,.woocommerce button.button:hover,.woocommerce input.button[type^="submit"]:hover,.woocommerce-page #respond input#submit:hover,.woocommerce-page a.button:hover,.woocommerce-page button.button:hover,.woocommerce-page input.button[type^="submit"]:hover,.woocommerce #respond input#submit[disabled]:hover:disabled,.woocommerce a.button[disabled]:hover:disabled,.woocommerce button.button[disabled]:hover:disabled,.woocommerce input.button[type^="submit"][disabled]:hover:disabled,.woocommerce-page #respond input#submit[disabled]:hover:disabled,.woocommerce-page a.button[disabled]:hover:disabled,.woocommerce-page button.button[disabled]:hover:disabled,.woocommerce-page input.button[type^="submit"][disabled]:hover:disabled,.btn:focus,button:focus,.button:focus,input[type="button"]:focus,input[type="reset"]:focus,input[type="submit"]:focus,.vc_btn3:focus,.clear-all:focus,.woocommerce #respond input#submit:focus,.woocommerce a.button:focus,.woocommerce button.button:focus,.woocommerce input.button[type^="submit"]:focus,.woocommerce-page #respond input#submit:focus,.woocommerce-page a.button:focus,.woocommerce-page button.button:focus,.woocommerce-page input.button[type^="submit"]:focus,.woocommerce #respond input#submit[disabled]:focus:disabled,.woocommerce a.button[disabled]:focus:disabled,.woocommerce button.button[disabled]:focus:disabled,.woocommerce input.button[type^="submit"][disabled]:focus:disabled,.woocommerce-page #respond input#submit[disabled]:focus:disabled,.woocommerce-page a.button[disabled]:focus:disabled,.woocommerce-page button.button[disabled]:focus:disabled,.woocommerce-page input.button[type^="submit"][disabled]:focus:disabled, .woocommerce #respond input#submit.alt:hover, .woocommerce a.button.alt:hover, .woocommerce button.button.alt:hover, .woocommerce input.button.alt:hover{color:'.get_theme_mod('color_hover','#fff').'}';
		$custom_css .= '.btn:hover,button:hover,.button:hover,input[type="button"]:hover,input[type="reset"]:hover,input[type="submit"]:hover,.vc_btn3:hover,.clear-all:hover,.woocommerce #respond input#submit:hover,.woocommerce a.button:hover,.woocommerce button.button:hover,.woocommerce input.button[type^="submit"]:hover,.woocommerce-page #respond input#submit:hover,.woocommerce-page a.button:hover,.woocommerce-page button.button:hover,.woocommerce-page input.button[type^="submit"]:hover,.woocommerce #respond input#submit[disabled]:hover:disabled,.woocommerce a.button[disabled]:hover:disabled,.woocommerce button.button[disabled]:hover:disabled,.woocommerce input.button[type^="submit"][disabled]:hover:disabled,.woocommerce-page #respond input#submit[disabled]:hover:disabled,.woocommerce-page a.button[disabled]:hover:disabled,.woocommerce-page button.button[disabled]:hover:disabled,.woocommerce-page input.button[type^="submit"][disabled]:hover:disabled,.btn:focus,button:focus,.button:focus,input[type="button"]:focus,input[type="reset"]:focus,input[type="submit"]:focus,.vc_btn3:focus,.clear-all:focus,.woocommerce #respond input#submit:focus,.woocommerce a.button:focus,.woocommerce button.button:focus,.woocommerce input.button[type^="submit"]:focus,.woocommerce-page #respond input#submit:focus,.woocommerce-page a.button:focus,.woocommerce-page button.button:focus,.woocommerce-page input.button[type^="submit"]:focus,.woocommerce #respond input#submit[disabled]:focus:disabled,.woocommerce a.button[disabled]:focus:disabled,.woocommerce button.button[disabled]:focus:disabled,.woocommerce input.button[type^="submit"][disabled]:focus:disabled,.woocommerce-page #respond input#submit[disabled]:focus:disabled,.woocommerce-page a.button[disabled]:focus:disabled,.woocommerce-page button.button[disabled]:focus:disabled,.woocommerce-page input.button[type^="submit"][disabled]:focus:disabled, .woocommerce #respond input#submit.alt:hover, .woocommerce a.button.alt:hover, .woocommerce button.button.alt:hover, .woocommerce input.button.alt:hover {background-color:'.get_theme_mod('background_hover','#010101').'}';
		$custom_css .= '.btn:hover,button:hover,.button:hover,input[type="button"]:hover,input[type="reset"]:hover,input[type="submit"]:hover,.vc_btn3:hover,.clear-all:hover,.woocommerce #respond input#submit:hover,.woocommerce a.button:hover,.woocommerce button.button:hover,.woocommerce input.button[type^="submit"]:hover,.woocommerce-page #respond input#submit:hover,.woocommerce-page a.button:hover,.woocommerce-page button.button:hover,.woocommerce-page input.button[type^="submit"]:hover,.woocommerce #respond input#submit[disabled]:hover:disabled,.woocommerce a.button[disabled]:hover:disabled,.woocommerce button.button[disabled]:hover:disabled,.woocommerce input.button[type^="submit"][disabled]:hover:disabled,.woocommerce-page #respond input#submit[disabled]:hover:disabled,.woocommerce-page a.button[disabled]:hover:disabled,.woocommerce-page button.button[disabled]:hover:disabled,.woocommerce-page input.button[type^="submit"][disabled]:hover:disabled,.btn:focus,button:focus,.button:focus,input[type="button"]:focus,input[type="reset"]:focus,input[type="submit"]:focus,.vc_btn3:focus,.clear-all:focus,.woocommerce #respond input#submit:focus,.woocommerce a.button:focus,.woocommerce button.button:focus,.woocommerce input.button[type^="submit"]:focus,.woocommerce-page #respond input#submit:focus,.woocommerce-page a.button:focus,.woocommerce-page button.button:focus,.woocommerce-page input.button[type^="submit"]:focus,.woocommerce #respond input#submit[disabled]:focus:disabled,.woocommerce a.button[disabled]:focus:disabled,.woocommerce button.button[disabled]:focus:disabled,.woocommerce input.button[type^="submit"][disabled]:focus:disabled,.woocommerce-page #respond input#submit[disabled]:focus:disabled,.woocommerce-page a.button[disabled]:focus:disabled,.woocommerce-page button.button[disabled]:focus:disabled,.woocommerce-page input.button[type^="submit"][disabled]:focus:disabled,.woocommerce #respond input#submit.alt:hover, .woocommerce a.button.alt:hover, .woocommerce button.button.alt:hover, .woocommerce input.button.alt:hover {border-color:'.get_theme_mod('border_hover','#010101').'}';


		wp_add_inline_style('wdjewelry-main.css',$custom_css);
	}

}		