<?php
				$TS_VCSC_VisualComposer_Element = array(
					"name"								=> esc_html__("WD Testimonials ", "wdjewelry"),
					"base"								=> "ts_testimonial_custom",
					"class"								=> "",
					"icon"								=> "ts-composer-element-icon-testimonial-slider-category",
					"category"							=> esc_html__("WPDance Elements", "wdjewelry"),
					"description"						=> esc_html__("Place a Testimonial Slider (by Category)", "wdjewelry"),
					"admin_enqueue_js"            		=> "",
					"admin_enqueue_css"           		=> "",
					"params"							=> array(
						// Content Settings
						array(
							"type"                      => "seperator",
							"heading"                   => "",
							"param_name"                => "seperator_1",
							"value"						=> "",
							"seperator"					=> "Content Settings",
							"description"               => esc_html__( "", "wdjewelry" )
						),
						array(
							"type"                      => "custompostcat",
							"heading"                   => esc_html__( "Testimonial Categories", "wdjewelry" ),
							"param_name"                => "testimonialcat",
							"posttype"                  => "ts_testimonials",
							"posttaxonomy"              => "ts_testimonials_category",
							"taxonomy"              	=> "ts_testimonials_category",
							"postsingle"				=> "Testimonial",
							"postplural"				=> "Testimonials",
							"postclass"					=> "testimonial",
							"value"                     => "",
							"description"               => esc_html__( "Please select the testimonial categories you want to use for the slider.", "wdjewelry" )
						),
						array(
							"type"                      => "dropdown",
							"heading"                   => esc_html__( "Design", "wdjewelry" ),
							"param_name"                => "style",
							"value"                     => array(
								esc_html__( 'Style 1', "wdjewelry" )          => "style1",
								esc_html__( 'Style 2', "wdjewelry" )          => "style2",
								esc_html__( 'Style 3', "wdjewelry" )          => "style3",
								esc_html__( 'Style 4', "wdjewelry" )          => "style4",
							),
							"description"               => "",
							"admin_label"               => true,
							"dependency"                => ""
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Show Autor Name", "wdjewelry" ),
							"param_name"                => "show_author",
							"value"                     => "true",
							"admin_label"		        => true,
							"description"               => esc_html__( "Switch the toggle if you want to show the author name for the testimonial.", "wdjewelry" )
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Show Avatar", "wdjewelry" ),
							"param_name"                => "show_avatar",
							"value"                     => "true",
							"admin_label"		        => true,
							"description"               => esc_html__( "Switch the toggle if you want to show the user avatar for the testimonial.", "wdjewelry" )
						),
						// Slider Settings
						array(
							"type"                      => "seperator",
							"heading"                   => "",
							"param_name"                => "seperator_2",
							"value"						=> "",
							"seperator"					=> "Slider Settings",
							"description"               => "",
							"group" 			        => "Slider Settings",
						),
						array(
							"type" 						=> "css3animations",
							"class" 					=> "",
							"heading" 					=> esc_html__("In-Animation Type", "wdjewelry"),
							"param_name" 				=> "animation_in",
							"standard"					=> "false",
							"prefix"					=> "ts-viewport-css-",
							"connector"					=> "css3animations_in",
							"default"					=> "flipInX",
							"value" 					=> "",
							"admin_label"				=> false,
							"description" 				=> esc_html__("Select the CSS3 in-animation you want to apply to the slider.", "wdjewelry"),
							"dependency"            	=> "",
							"group" 			        => "Slider Settings",
						),
						array(
							"type"                      => "hidden_input",
							"heading"                   => esc_html__( "In-Animation Type", "wdjewelry" ),
							"param_name"                => "css3animations_in",
							"value"                     => "",
							"admin_label"		        => true,
							"description"               => "",
							"dependency"            	=> "",
							"group" 			        => "Slider Settings",
						),						
						array(
							"type" 						=> "css3animations",
							"class" 					=> "",
							"heading" 					=> esc_html__("Out-Animation Type", "wdjewelry"),
							"param_name" 				=> "animation_out",
							"standard"					=> "false",
							"prefix"					=> "ts-viewport-css-",
							"connector"					=> "css3animations_out",
							"default"					=> "slideOutDown",
							"value" 					=> "",
							"admin_label"				=> false,
							"description" 				=> esc_html__("Select the CSS3 out-animation you want to apply to the slider.", "wdjewelry"),
							"dependency"            	=> "",
							"group" 			        => "Slider Settings",
						),
						array(
							"type"                      => "hidden_input",
							"heading"                   => esc_html__( "Out-Animation Type", "wdjewelry" ),
							"param_name"                => "css3animations_out",
							"value"                     => "",
							"admin_label"		        => true,
							"description"               => "",
							"dependency"            	=> "",
							"group" 			        => "Slider Settings",
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Animate on Mobile", "wdjewelry" ),
							"param_name"                => "animation_mobile",
							"value"                     => "false",
							"description"               => esc_html__( "Switch the toggle if you want to show the CSS3 animations on mobile devices.", "wdjewelry" ),
							"group" 			        => "Slider Settings",
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Auto-Height", "wdjewelry" ),
							"param_name"                => "auto_height",
							"value"                     => "true",
							"admin_label"		        => true,
							"description"               => esc_html__( "Switch the toggle if you want the slider to auto-adjust its height.", "wdjewelry" ),
							"group" 			        => "Slider Settings",
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "RTL Page", "wdjewelry" ),
							"param_name"                => "page_rtl",
							"value"                     => "false",
							"description"               => esc_html__( "Switch the toggle if the slider is used on a page with RTL (Right-To-Left) alignment.", "wdjewelry" ),
							"dependency"                => "Slider Settings"
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Auto-Play", "wdjewelry" ),
							"param_name"                => "auto_play",
							"value"                     => "false",
							"admin_label"		        => true,
							"description"               => esc_html__( "Switch the toggle if you want the auto-play the slider on page load.", "wdjewelry" ),
							"group" 			        => "Slider Settings",
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Show Play / Pause", "wdjewelry" ),
							"param_name"                => "show_playpause",
							"value"                     => "true",
							"description"               => esc_html__( "Switch the toggle if you want to show a play / pause button to control the autoplay.", "wdjewelry" ),
							"dependency" 				=> array("element" 	=> "auto_play", "value" 	=> "true"),
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Show Progressbar", "wdjewelry" ),
							"param_name"                => "show_bar",
							"value"                     => "true",
							"description"               => esc_html__( "Switch the toggle if you want to show a progressbar during auto-play.", "wdjewelry" ),
							"dependency" 				=> array("element" 	=> "auto_play", "value" 	=> "true"),
							"group" 			        => "Slider Settings",
						),
						array(
							"type"                      => "colorpicker",
							"heading"                   => esc_html__( "Progressbar Color", "wdjewelry" ),
							"param_name"                => "bar_color",
							"value"                     => "#dd3333",
							"description"               => esc_html__( "Define the color of the animated progressbar.", "wdjewelry" ),
							"dependency" 				=> array("element" 	=> "auto_play", "value" 	=> "true"),
							"group" 			        => "Slider Settings",
						),
						array(
							"type"                      => "nouislider",
							"heading"                   => esc_html__( "Auto-Play Speed", "wdjewelry" ),
							"param_name"                => "show_speed",
							"value"                     => "5000",
							"min"                       => "1000",
							"max"                       => "20000",
							"step"                      => "100",
							"unit"                      => 'ms',
							"description"               => esc_html__( "Define the speed used to auto-play the slider.", "wdjewelry" ),
							"dependency" 				=> array("element" 	=> "auto_play","value" 	=> "true"),
							"group" 			        => "Slider Settings",
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Stop on Hover", "wdjewelry" ),
							"param_name"                => "stop_hover",
							"value"                     => "true",
							"description"               => esc_html__( "Switch the toggle if you want the stop the auto-play while hovering over the slider.", "wdjewelry" ),
							"dependency"                => array( 'element' => "auto_play", 'value' => 'true' ),
							"group" 			        => "Slider Settings",
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Show Top Navigation", "wdjewelry" ),
							"param_name"                => "show_navigation",
							"value"                     => "true",
							"description"               => esc_html__( "Switch the toggle if you want to show left/right navigation buttons for the slider.", "wdjewelry" ),
							"group" 			        => "Slider Settings",
						),
						array(
							"type"              	    => "switch_button",
							"heading"                   => esc_html__( "Show Dot Navigation", "wdjewelry" ),
							"param_name"                => "show_dots",
							"value"                     => "true",
							"description"               => esc_html__( "Switch the toggle if you want to show dot navigation buttons below the slider.", "wdjewelry" ),
							"dependency"                => "Slider Settings"
						),
						// Other Settings
						array(
							"type"                      => "seperator",
							"heading"                   => "",
							"param_name"                => "seperator_3",
							"value"						=> "",
							"seperator"					=> "Other Settings",
							"description"               => "",
							"group" 			        => "Other Settings",
						),
						array(
							"type"                      => "nouislider",
							"heading"                   => esc_html__( "Margin: Top", "wdjewelry" ),
							"param_name"                => "margin_top",
							"value"                     => "0",
							"min"                       => "0",
							"max"                       => "200",
							"step"                      => "1",
							"unit"                      => 'px',
							"description"               => esc_html__( "Select the top margin for the element.", "wdjewelry" ),
							"group" 			        => "Other Settings",
						),
						array(
							"type"                      => "nouislider",
							"heading"                   => esc_html__( "Margin: Bottom", "wdjewelry" ),
							"param_name"                => "margin_bottom",
							"value"                     => "0",
							"min"                       => "0",
							"max"                       => "200",
							"step"                      => "1",
							"unit"                      => 'px',
							"description"               => esc_html__( "Select the bottom margin for the element.", "wdjewelry" ),
							"group" 			        => "Other Settings",
						),
						array(
							"type"                      => "textfield",
							"heading"                   => esc_html__( "Define ID Name", "wdjewelry" ),
							"param_name"                => "el_id",
							"value"                     => "",
							"description"               => esc_html__( "Enter an unique ID for the element.", "wdjewelry" ),
							"group" 			        => "Other Settings",
						),
						array(
							"type"                      => "textfield",
							"heading"                   => esc_html__( "Extra Class Name", "wdjewelry" ),
							"param_name"                => "el_class",
							"value"                     => "",
							"description"               => esc_html__( "Enter a class name for the element.", "wdjewelry" ),
							"group" 			        => "Other Settings",
						),
						// Load Custom CSS/JS File
						array(
							"type"                      => "load_file",
							"heading"                   => "",
							"param_name"                => "el_file1",
							"value"                     => "",
							"file_type"                 => "js",
							"file_id"         			=> "ts-extend-element",
							"file_path"                 => "js/ts-visual-composer-extend-element.min.js",
							"description"               => esc_html__( "", "wdjewelry" )
						),
					)
				);
vc_map($TS_VCSC_VisualComposer_Element);